# Generated by Django 5.0.3 on 2025-02-26 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funko_import', '0025_venta_detalleventa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='brilla',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='esEspecial',
            field=models.BooleanField(),
        ),
    ]
