# Generated by Django 5.0.3 on 2025-02-26 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funko_import', '0025_venta_detalleventa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codigoseguimiento',
            name='id_factura',
        ),
        migrations.AddField(
            model_name='codigoseguimiento',
            name='id1',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='funko_import.venta'),
            preserve_default=False,
        ),
    ]
