# Generated by Django 5.0.3 on 2025-02-26 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funko_import', '0026_remove_codigoseguimiento_id_factura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='codigo_seguimiento',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='estado',
            field=models.CharField(choices=[('en_espera', 'En espera'), ('despachado', 'Despachado'), ('cancelado', 'Cancelado')], default='en_espera', max_length=20),
        ),
    ]
