# Generated by Django 5.0.3 on 2025-02-26 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funko_import', '0027_venta_codigo_seguimiento_alter_venta_estado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resenacomentario',
            old_name='idProducto',
            new_name='id_producto',
        ),
    ]
