# Generated by Django 5.0.3 on 2025-02-26 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funko_import', '0028_rename_idproducto_resenacomentario_id_producto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resenacomentario',
            old_name='id_producto',
            new_name='idProducto',
        ),
    ]
