# Generated by Django 5.0.3 on 2025-02-27 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funko_import', '0030_rename_id_usuario_factura_idusuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='descuento',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
